env = Environment(CPPPATH='/usr/include')
env.Program('BouncingMushroom.exe', Glob('*.cpp'), 
    LIBS = ['sfml-window','sfml-system','sfml-graphics'], 
    LIBPATH = ['/usr/lib', '/usr/local/lib'],
    CXXFLAGS="-std=c++0x -g"
    )