env = Environment(    
    LIBS = ['sfml-window','sfml-system','sfml-graphics'], 
    LIBPATH = ['/usr/lib', '/usr/local/lib'],
    CXXFLAGS="-std=c++11 -g")
env.Program('MovingMushroom.exe', Glob('*.cpp'))